lsi: false
safe: true
source: [C:\Users\Noah Chow\Documents\GitHub\github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge